#!/bin/bash
#
# chkconfig: 35 90 12
# description: Sniffer daemon
#

# Get function from functions library
. /etc/init.d/functions

# Start the service sniffer_daemon
start() {
        initlog -c "echo -n Starting sniffer daemon: "
        /usr/bin/sniffer_daemon &
        ### Create the lock file ###
        touch /var/lock/subsys/sniffer_daemon
        success $"sniffer_daemon startup"
        echo
}

# Restart the service sniffer_daemon
stop() {
        initlog -c "echo -n Stopping sniffer daemon: "
        kill -9 $(pidof sniffer_daemon)
        ### Now, delete the lock file ###
        rm -f /var/lock/subsys/sniffer_daemon
        echo
}

### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status sniffer_daemon
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac

exit 0
